#!/bin/bash

set -e

if [ ! "$(type -P dialog)" -o ! "$(type -P git-pulls)" ]; then
	if grep -q Ubuntu /etc/issue || grep -q Debian /etc/issue ]; then
		if [ ! "$(type -P sudo)" ]; then
			echo 'su -c "apt-get install rubygems"; su -c "gem install git-pulls"'
			su -c "apt-get install rubygems dialog"
			su -c "gem install git-pulls"
		else
			echo "sudo apt-get install rubygems; sudo gem install git-pulls"
			sudo apt-get install rubygems dialog
			sudo gem install git-pulls
		fi
	else
		echo "Whut fuck os you have ?! install dialog and git-pulls NOW"
		exit
	fi
fi



git pulls update

if ! git config --get-regexp "remote.*fetch" "/pr/" > /dev/null; then
	echo "You didn't add the the pull requests refs, add ?"
	read -p "Execute git config --add remote.origin.fetch \"+refs/pull/*/head:refs/remotes/origin/pr/*\"' ? [N/y] " CONFIRM
	if [ "$CONFIRM" == "y" ]; then
		git config --add remote.origin.fetch "+refs/pull/*/head:refs/remotes/origin/pr/*"
	fi
fi

PR_DIALOG_ARGS=()
while read LINE; do
	PR_DIALOG_ARGS+=("${LINE%% *}" "${LINE#* }")
done < <(git pulls list | tail -n +2)
PR=$(dialog --stdout --menu "Merge pull request: " 15 120 8 \
		"${PR_DIALOG_ARGS[@]}")

clear

echo fetching from origin...
git fetch origin
git merge --squash remotes/origin/pr/$PR

git pulls list | grep "^$PR " | sed -re 's/^\w+\s+\w+\/\w+\s+//' -e 's/[^ ]+ *$//' >  "$(git rev-parse --git-dir)/SQUASH_MSG"

